### ISSUE TITLE
Improvements to alert threshold when using percent

### ISSUE THREAD

**Issue by lmuhlha** [spotify/spotify-heroic-datasource#111]
When adding an alert on a percentage threshold, the value needs to be entered divided by 100 since the input isn't read as a percent, which can be confusing to end users. Some may expect the value should be entered as the % value since the panel is already "using % units". 

For example, entering 0.1 is 10%

![image](https://user-images.githubusercontent.com/16561599/73692507-72081500-46a2-11ea-94a1-1fa16b4cf33c.png)

**Comment by ryanvazquez** [comment]
These values cannot be modified by the datasource.

**Comment by lmuhlha** [comment]
Grafana UI problem?

**Comment by ryanvazquez** [comment]
> Grafana UI problem?

Yep. Grafana offers the ability to toggle the Alert Tab UI on/off via config but the tab itself is not configurable.

**Comment by ryanvazquez** [comment]
Closing this issue as it pertains to Grafana, not the datasource plugin.
