### ISSUE TITLE
Publish plugin to Grafana

### ISSUE THREAD

**Issue by dmichel1** [spotify/spotify-heroic-datasource#56]
This plugin should become the official one and replace https://grafana.com/plugins/udoprog-heroic-datasource

**Comment by sjoeboo** [comment]
Ticket #5713 opened on grafana.com, also started asking in Slack.

**Comment by sjoeboo** [comment]
instructed we should use/check out: https://www.npmjs.com/package/@grafana/toolkit

**Comment by sjoeboo** [comment]
https://github.com/grafana/grafana/issues/17186
