### ISSUE TITLE
Common tag suggestions

### ISSUE THREAD

**Issue by dmichel1** [spotify/spotify-heroic-datasource#57]
Certain tags like `what` are not being showing up in the suggestions. It would be good if we could artificially boost the more common tags if they exist.

With alien we always show the below suggestions when starting from nothing.

![Screen Shot 2019-07-02 at 3 55 59 PM](https://user-images.githubusercontent.com/677960/60542421-e8463280-9ce1-11e9-97a7-b3398375635b.png)

**Comment by sjoeboo** [comment]
Done
