### ISSUE TITLE
Add query context to /query/batch

### ISSUE THREAD

**Issue by dmichel1** [spotify/spotify-heroic-datasource#63]
When a query is made to heroic, it should add context to the request around what dashboard and graph is sending the query.

Alien does something like...

![Screen Shot 2019-08-06 at 9 54 30 AM](https://user-images.githubusercontent.com/677960/62546437-76f22600-b831-11e9-91a5-d3b929495a8a.png)

As part of the query payload `clientContext` can be added to achieve this. Heroic accepts arbitrary json fields.

Adding this to the plugin makes it easier to discovery where potential "bad" queries are being made, as `clientContext` gets added to the heroic query logs.

**Comment by dmichel1** [comment]
`httpContext` should be added as well that would include the `clientId`

**Comment by ryanvazquez** [comment]
Do you mean `httpContext` should be added to the `clientContext` field? Heroic 400's when this is added directly to the query payload.

**Comment by dmichel1** [comment]
@ryanmvazquez ah looking at the code looks like `X-Client-Id` should be header. 

https://github.com/spotify/heroic/blob/master/heroic-core/src/main/java/com/spotify/heroic/http/CoreHttpContextFactory.java

**Comment by ryanvazquez** [comment]
Gotcha! No prob.
